FROM alpine:latest

RUN apk add --no-cache zip bash curl mariadb mariadb-client tzdata

# Set the timezone (e.g., Asia/Tehran)
ENV TZ=Asia/Tehran
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY backup.sh /usr/local/bin/backup.sh
RUN chmod +x /usr/local/bin/backup.sh

RUN echo "*/30 * * * * /usr/local/bin/backup.sh" >> /etc/crontabs/root

CMD ["crond", "-f"]
