services:
  apache:
    build:
      context: .
    container_name: ${folder}
    hostname: ${domain}
    volumes:
      - /php-sites/${folder}/root:/app/
    env_file:
      - etc/environment.yml
      # - etc/environment.development.yml
      - etc/environment.production.yml
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
    networks:
      - local
      - www

  mariadb:
    image: mariadb:latest
    container_name: ${folder}-db
    env_file:
      - /php-sites/${folder}/.env
    volumes:
      - /php-sites/${folder}/mariadb:/var/lib/mysql
    restart: always
    networks:
      - local
      - database-monitor

  backup-runner:
    container_name: ${folder}-backup-runner
    build:
      context: .
      dockerfile: ./Dockerfile-backup
    volumes:
      - /php-sites/${folder}:/source:ro
      - /php-sites/${folder}/backup:/backup
    env_file:
      - /php-sites/${folder}/.env
    deploy:
      resources:
        limits:
          memory: 256MB
          cpus: '0.5'

networks:
  local:
    name: ${folder}
  www:
    name: www
    external: true
  database-monitor:
    name: database-monitor
    external: true

#command: domain=domain.com folder=domain-com docker compose -f ./docker-compose.yml up -d --build
