version: '3.8'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    networks:
      - database-monitor
      - www
networks:
  www:
    name: www
    external: true
  database-monitor:
    name: database-monitor
