
# Use the official OpenLiteSpeed image
FROM litespeedtech/openlitespeed:latest


# Install dependencies
RUN apt-get update && \
    apt-get install -y wget unzip


# Download and install ionCube Loader
RUN wget https://downloads.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.zip
RUN unzip ioncube_loaders_lin_x86-64.zip && \
    mkdir -p /usr/local/lsws/lsphp83/etc/php/8.3/conf.d && \
    cp ioncube/ioncube_loader_lin_8.3.so /usr/local/lsws/lsphp83/lib/php/ && \
    echo "zend_extension = /usr/local/lsws/lsphp83/lib/php/ioncube_loader_lin_8.3.so" > /usr/local/lsws/lsphp83/etc/php/8.3/mods-available/ioncube.ini && \
    ln -s /usr/local/lsws/lsphp83/etc/php/8.3/mods-available/ioncube.ini /usr/local/lsws/lsphp83/etc/php/8.3/conf.d/00-ioncube.ini && \
    rm -rf ioncube_loaders_lin_x86-64.zip ioncube


# Set the working directory
WORKDIR /var/www/vhosts/localhost/

USER nobody

# Set permissions for the web root directory
RUN mkdir -p html && \     
    chown -R nobody:nogroup /var/www/


# Expose ports
EXPOSE 80 443 7080

# Start OpenLiteSpeed
CMD ["/usr/local/lsws/bin/lswsctrl", "start"]